# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-neon
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-neon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
#    network_mode: host
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.141.59-neon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
#    network_mode: host
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
networks:
  default:
    external:
      name: ta_workshop_default
#  test_container:
#    container_name: test_container
#    depends_on:
#      - selenium-hub
#      - chrome
#      - firefox
#    build: .
#    volumes:
#      - /var/lib/jenkins/workspace/ta_workshop/output:/output_folder
#    network_mode: host

